version: "2"
services:
    rancher_server:
        image: rancher/server:stable
        restart: unless-stopped
        volumes:
            - /opt/rancher/mysql-var:/var/lib/mysql
        ports:
            - 8080:8080
    web_server:
        image: nginx:stable
        restart: unless-stopped
        depends_on:
            - rancher_server
        links:
            - rancher_server
        volumes:
            - /etc/letsencrypt/live/dsjh64.net/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            - /etc/letsencrypt/live/dsjh64.net/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
            - /opt/rancher/nginx.conf:/etc/nginx/nginx.conf:ro
            - /opt/rancher/rancher.conf:/etc/nginx/conf.d/rancher.conf:ro
        ports:
            - 80:80
            - 443:443
